"""add error fields to syncjob

Revision ID: 4bef101a2b2c
Revises: c057e66e8eed
Create Date: 2026-06-05 08:25:28.619240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bef101a2b2c'
down_revision = 'c057e66e8eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('correlation_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_job', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('last_error')

    # ### end Alembic commands ###
