"""add workspace_id to webhook

Revision ID: c057e66e8eed
Revises: 766eae20b864
Create Date: 2026-06-04 22:23:34.733612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c057e66e8eed'
down_revision = '766eae20b864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_webhook_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_webhook_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_webhook_event_workspace_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
